apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  namespace: spring
  labels:
    app: spring
spec:
  selector:
    matchLabels:
      app: spring
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: spring
          image: srujankumar25/srujan-1
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi

          ports:
            - containerPort: 8000
              name: spring
      restartPolicy: Always
