apiVersion: apps/v1
kind: Deployment
metadata:
  name:  organization-deployment
  namespace: org-service
  labels:
    app:  organization-service
spec:
  selector:
    matchLabels:
      app: organization-service
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  organization-service
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  organization-service
        image: srujankumar25/organization-service:org-service-1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: organization-service
  namespace: org-service
spec:
  selector:
    app: organization-service
  type: ClusterIP
  ports:
  - port: 8080

---
